### ISSUE TITLE
akka-sample-persistence error

### ISSUE THREAD

**Issue by yangguang760** [akka/akka-samples#43]
Both akka-sample-persistence-scala and akka-sample-persistence-java throws error as followings:

"无效的参数" means invalid argument.

```
yang@yang-VirtualBox:~/E/scalaProj/akka-samples/akka-sample-persistence-java$ sbt run
[info] Loading global plugins from /home/yang/.sbt/0.13/plugins
[info] Loading project definition from /home/yang/E/scalaProj/akka-samples/akka-sample-persistence-java/project
[info] Updating {file:/home/yang/E/scalaProj/akka-samples/akka-sample-persistence-java/project/}akka-sample-persistence-java-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to akka-sample-persistence-java (in build file:/home/yang/E/scalaProj/akka-samples/akka-sample-persistence-java/)
[info] Updating {file:/home/yang/E/scalaProj/akka-samples/akka-sample-persistence-java/}akka-sample-persistence-java...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 3 Java sources to /home/yang/E/scalaProj/akka-samples/akka-sample-persistence-java/target/scala-2.12/classes...
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] sample.persistence.PersistentActorExample
 [2] sample.persistence.PersistentActorFailureExample
 [3] sample.persistence.SnapshotExample

Enter number: 1

[info] Running sample.persistence.PersistentActorExample 
[ERROR] [10/10/2017 09:57:52.140] [example-akka.actor.default-dispatcher-2] [akka://example/system/akka.persistence.journal.leveldb] 无效的参数
akka.actor.ActorInitializationException: akka://example/system/akka.persistence.journal.leveldb: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:191)
	at akka.actor.ActorCell.create(ActorCell.scala:608)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: 无效的参数
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:926)
	at org.iq80.leveldb.impl.MMapLogWriter.<init>(MMapLogWriter.java:63)
	at org.iq80.leveldb.impl.Logs.createLogWriter(Logs.java:36)
	at org.iq80.leveldb.impl.VersionSet.initializeIfNeeded(VersionSet.java:106)
	at org.iq80.leveldb.impl.VersionSet.<init>(VersionSet.java:91)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:178)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:59)
	at akka.persistence.journal.leveldb.LeveldbStore.preStart(LeveldbStore.scala:178)
	at akka.persistence.journal.leveldb.LeveldbStore.preStart$(LeveldbStore.scala:177)
	at akka.persistence.journal.leveldb.LeveldbJournal.preStart(LeveldbJournal.scala:23)
	at akka.actor.Actor.aroundPreStart(Actor.scala:522)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:522)
	at akka.persistence.journal.leveldb.LeveldbJournal.aroundPreStart(LeveldbJournal.scala:23)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	... 7 more

```

**Comment by yangguang760** [comment]
This may be the issue of VirtualBox.
After changing the location out of shared filesystem, no exception any more.
