### ISSUE TITLE
WorkerSystem AssociationError

### ISSUE THREAD

**Issue by anant1525** [akka/akka-samples#59]
Hi,

I am working on upgrading the akka distributed workers (in similar lines with the distributed works example), master is ClusterSingletonManager and WorkersSystem is coming up, but getting the strange Association error.

Using Akka 2.4.17 also faced the same issue with akka 2.5.4.

Please suggest, looks like we are stuck here.   

```
2018-03-30 10:31:02,963 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-25) [INFO] [03/30/2018 10:31:02.953] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4002]
2018-03-30 10:31:02,965 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-30) [INFO] [03/30/2018 10:31:02.960] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4002]
2018-03-30 10:31:03,046 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-15) [INFO] [03/30/2018 10:31:03.021] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
2018-03-30 10:31:03,083 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-28) [INFO] [03/30/2018 10:31:03.077] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4003]
2018-03-30 10:31:03,100 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-35) [INFO] [03/30/2018 10:31:03.077] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4003]
2018-03-30 10:31:03,145 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-14) [INFO] [03/30/2018 10:31:03.144] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
2018-03-30 10:31:03,185 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-27) [INFO] [03/30/2018 10:31:03.183] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4004]
2018-03-30 10:31:03,186 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-29) [INFO] [03/30/2018 10:31:03.184] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4004]
2018-03-30 10:31:03,231 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-10) [INFO] [03/30/2018 10:31:03.230] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
2018-03-30 10:31:03,259 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-24) [INFO] [03/30/2018 10:31:03.255] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4005]
2018-03-30 10:31:03,261 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-28) [INFO] [03/30/2018 10:31:03.256] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4005]
2018-03-30 10:31:03,325 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-13) [INFO] [03/30/2018 10:31:03.324] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
_**2018-03-30 10:31:03,331 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) [ERROR] **[03/30/2018 10:31:03.330] [WorkerSystem-akka.remote.default-remote-dispatcher-22] [akka.tcp://WorkerSystem@127.0.0.1:4002/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterSystem%40127.0.0.1%3A2551-0/endpointWriter] AssociationError [akka.tcp://WorkerSystem@127.0.0.1:4002] -> [akka.tcp://ClusterSystem@127.0.0.1:2551]: Error [[B cannot be cast to [C] [
2018-03-30 10:31:03,331 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) java.lang.ClassCastException: [B cannot be cast to [C****_
2018-03-30 10:31:03,332 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-5)   at deployment.jaxrpc.war//akka.remote.artery.FastHash$.ofString(LruBoundedCache.scala:18)
2018-03-30 10:31:03,332 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-5)   at deployment.jaxrpc.war//akka.remote.serialization.ActorRefResolveCache.hash(ActorRefResolveCache.scala:61)
2018-03-30 10:31:03,332 INFO  [stdout] (WorkerSystem-akka.actor.default-dispatcher-5)   at deployment.jaxrpc.war//akka.remote.serialization.ActorRefResolveCache.hash(ActorRefResolveCache.scala:55)
```

**Comment by anant1525** [comment]
hi,
really appreciate the reply/ help here.

**Comment by johanandren** [comment]
I'm pretty sure the example doesn't do any stuff related to `deployment.jaxrpc.war`, there is also no place in the sample that the system name `WorkerSystem` is used, so this is something that you have changed with the sample? Are you running multiple samples and hoping that they will connect to each other or something like that?

**Comment by anant1525** [comment]
Hi Johanadren,

Yes you are right, I was playing with the sample for understanding. 
Its just wrapped around Spring and deployed as war build.

Code sample is perfectly correct, I sorted the error. problem was 2.3 --> 2.5 explicitly mentioning the singleton name,
I mentioned the name which we were using as sample below, and code is working like a charm.

  ClusterSingletonProxy.props(
      "/user/master",      ClusterSingletonProxySettings.create(getContext().system()).withRole("backend").withSingletonName("singleton")),
  "masterProxy");

**Comment by johanandren** [comment]
Thanks for letting us know that you figured it out and what the problem was!
