### ISSUE TITLE
Transformation example in akka-sample-cluster-scala doesn't work partially.

### ISSUE THREAD

**Issue by Sraw** [akka/akka-samples#83]
System: Linux mint 19 with 4.15 kernel

I cannot fully run the transformation example. The problem is, I can launch two process, they cost around 100MB space of /dev/shm. And when I launch the third process, the usage of /dev/shm increses to 900MB. Further, when I try to launch the fourth process, it just eats all my space and throws an error:

```
[info] Warning: space is running low in /dev/shm (tmpfs) threshold=167,772,160 usable=95,424,512
[info] Warning: space is running low in /dev/shm (tmpfs) threshold=167,772,160 usable=45,088,768
[info] [ERROR] [11/05/2018 21:03:56.156] [ClusterSystem-akka.actor.default-dispatcher-12] [akka://ClusterSystem@127.0.0.1:57246/] swallowing exception during message send
[info] io.aeron.exceptions.RegistrationException: IllegalStateException : Insufficient usable storage for new log of length=50335744 in /dev/shm (tmpfs)
[info]  at io.aeron.ClientConductor.onError(ClientConductor.java:174)
[info]  at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:81)
[info]  at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
[info]  at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:56)
[info]  at io.aeron.ClientConductor.service(ClientConductor.java:660)
[info]  at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:696)
[info]  at io.aeron.ClientConductor.addPublication(ClientConductor.java:371)
[info]  at io.aeron.Aeron.addPublication(Aeron.java:259)
[info]  at akka.remote.artery.aeron.AeronSink$$anon$1.<init>(AeronSink.scala:103)
[info]  at akka.remote.artery.aeron.AeronSink.createLogicAndMaterializedValue(AeronSink.scala:100)
[info]  at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:630)
[info]  at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:450)
[info]  at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
[info]  at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:406)
[info]  at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:588)
[info]  at akka.remote.artery.Association.runOutboundOrdinaryMessagesStream(Association.scala:726)
[info]  at akka.remote.artery.Association.runOutboundStreams(Association.scala:657)
[info]  at akka.remote.artery.Association.associate(Association.scala:649)
[info]  at akka.remote.artery.AssociationRegistry.association(Association.scala:989)
[info]  at akka.remote.artery.ArteryTransport.association(ArteryTransport.scala:724)
[info]  at akka.remote.artery.ArteryTransport.send(ArteryTransport.scala:710)
[info]  at akka.remote.RemoteActorRef.$bang(RemoteActorRefProvider.scala:591)
[info]  at akka.actor.ActorRef.tell(ActorRef.scala:124)
[info]  at akka.actor.ActorSelection$.rec$1(ActorSelection.scala:265)
[info]  at akka.actor.ActorSelection$.deliverSelection(ActorSelection.scala:269)
[info]  at akka.actor.ActorSelection.tell(ActorSelection.scala:46)
[info]  at akka.actor.ScalaActorSelection.$bang(ActorSelection.scala:280)
[info]  at akka.actor.ScalaActorSelection.$bang$(ActorSelection.scala:280)
[info]  at akka.actor.ActorSelection$$anon$1.$bang(ActorSelection.scala:198)
[info]  at akka.cluster.ClusterCoreDaemon.gossipTo(ClusterDaemon.scala:1330)
[info]  at akka.cluster.ClusterCoreDaemon.gossip(ClusterDaemon.scala:1047)
[info]  at akka.cluster.ClusterCoreDaemon.gossipTick(ClusterDaemon.scala:1010)
[info]  at akka.cluster.ClusterCoreDaemon$$anonfun$initialized$1.applyOrElse(ClusterDaemon.scala:496)
[info]  at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
[info]  at akka.actor.Actor.aroundReceive(Actor.scala:517)
[info]  at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[info]  at akka.cluster.ClusterCoreDaemon.aroundReceive(ClusterDaemon.scala:295)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:557)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[info]  at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[info]  at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]  at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]  at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]  at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Then all processes die. So my question is why it needs so much space? I have tested multiple times. It doesn't matter which process I launch, frontend or backend. They just eat significantly more space than the former one.
1: eat a little - some KBs
2: eat a little bit more - some MBs
3: eat a huge - some hundread MBs
4: don't know how much is enough

**Comment by patriknw** [comment]
In samples we should use Artery TCP to avoid such configuration issues with Aeron. I have created PR https://github.com/akka/akka-samples/pull/84

@Sraw You can try it by changing the application.conf to use:
```
    akka.remote.artery.enabled = on
    akka.remote.artery.transport = tcp
```

**Comment by Sraw** [comment]
It works perfectly after modification. Could you tell me what is the root cause?
When we don't specify tcp transport, artry is using udp? While artry's udp costs so much space? Is that normal?
Or may I misunderstand the configuration? It is using netty to transport message mainly.

Basically I think using more than 4G /dev/shm space only to launch 5 instances is not a desirable behavior. What causes that?

**Comment by patriknw** [comment]
Then it's using Aeron (with UPD). You can read more about the choice here https://doc.akka.io/docs/akka/current/remoting-artery.html#selecting-transport

It's possible to tune Aeron to use less resources e.g by reducing buffer sizes, and if running many instances on same machine one should use a shared media driver. However, it's easiest to start out with the tcp transport.

**Comment by Sraw** [comment]
Thanks a lot. So correct me if I understand wrongly:
1. This problem will only happen when running multiple instances on the same machine with Aeron UDP transport protocol.
2. The problem can be solved by using shared media driver or something else.
3. Using tcp protocol is good, but may not as good as Aeron UDP.

**Comment by dfurmans** [comment]
That was one of our BIG issue 
```
This problem will only happen when running multiple instances on the same machine with Aeron UDP transport protocol.
```
Finally we have a solution!!!! yeah :tada: 

```
	remote {
		artery {
			enabled = on
			transport = tcp
		}
	}
```
