### ISSUE TITLE
akka-sample-cluster-scala seems not running properly on my macbook

### ISSUE THREAD

**Issue by cosmir17** [akka/akka-samples#98]
Hello,

I pulled the akka-sample-cluster-scala project
https://github.com/akka/akka-samples/tree/2.5/akka-sample-cluster-scala

and ran [sbt "runMain sample.cluster.simple.SimpleClusterApp"] and I got the error messages below.

Any advice for me?

I ran
sbt "runMain sample.cluster.simple.SimpleClusterApp 2551"
sbt "runMain sample.cluster.simple.SimpleClusterApp 2552"
sbt "runMain sample.cluster.simple.SimpleClusterApp 0"

The result is same.

I am using a MacBookPro, mojave osx. I am using oracle java version 8.171

Thank you,
cosmir17

```
 sbt "runMain sample.cluster.simple.SimpleClusterApp"
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/sk/.sbt/1.0/plugins
[info] Loading settings for project akka-sample-cluster-scala-build from plugins.sbt ...
[info] Loading project definition from /Users/sk/IdeaProjects/akka-samples/akka-sample-cluster-scala/project
[info] Loading settings for project akka-sample-cluster-scala from build.sbt ...
[info] Set current project to akka-sample-cluster-scala (in build file:/Users/sk/IdeaProjects/akka-samples/akka-sample-cluster-scala/)
[info] Updating ...
[info] Done updating.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Packaging /Users/sk/IdeaProjects/akka-samples/akka-sample-cluster-scala/target/scala-2.12/akka-sample-cluster-scala_2.12-fec5470d.jar ...
[info] Done packaging.
[info] Running (fork) sample.cluster.simple.SimpleClusterApp 
[info] [INFO] [01/25/2019 22:53:44.304] [main] [akka.remote.artery.tcp.ArteryTcpTransport(akka://ClusterSystem)] Remoting started with transport [Artery tcp]; listening on address [akka://ClusterSystem@127.0.0.1:49529] with UID [-2464032911652136694]
[info] [INFO] [01/25/2019 22:53:44.325] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka://ClusterSystem@127.0.0.1:49529] - Starting up, Akka version [2.5.18] ...
[info] [INFO] [01/25/2019 22:53:44.446] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka://ClusterSystem@127.0.0.1:49529] - Registered cluster JMX MBean [akka:type=Cluster]
[info] [INFO] [01/25/2019 22:53:44.446] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka://ClusterSystem@127.0.0.1:49529] - Started up successfully
[info] [WARN] [01/25/2019 22:53:44.487] [ClusterSystem-akka.actor.default-dispatcher-3] [akka://ClusterSystem@127.0.0.1:49529/system/cluster/core/daemon/downingProvider] Don't use auto-down feature of Akka Cluster in production. See 'Auto-downing (DO NOT USE)' section of Akka Cluster documentation.
[info] [ERROR] [01/25/2019 22:53:44.521] [ClusterSystem-akka.actor.default-dispatcher-11] [akka.cluster.ClusterActorRefProvider] No root guardian at [akka.tcp://ClusterSystem@127.0.0.1:2551]
[info] java.lang.IllegalArgumentException: Wrong protocol of [akka.tcp://ClusterSystem@127.0.0.1:2551/], expected [akka]
[info] 	at akka.remote.RemoteActorRef.<init>(RemoteActorRefProvider.scala:533)
[info] 	at akka.remote.RemoteActorRefProvider.rootGuardianAt(RemoteActorRefProvider.scala:378)
[info] 	at akka.actor.ActorRefFactory.actorSelection(ActorRefProvider.scala:351)
[info] 	at akka.actor.ActorRefFactory.actorSelection$(ActorRefProvider.scala:345)
[info] 	at akka.actor.ActorCell.actorSelection(ActorCell.scala:431)
[info] 	at akka.cluster.JoinSeedNodeProcess$$anonfun$receive$4.$anonfun$applyOrElse$7(ClusterDaemon.scala:1562)
[info] 	at akka.cluster.JoinSeedNodeProcess$$anonfun$receive$4.$anonfun$applyOrElse$7$adapted(ClusterDaemon.scala:1562)
[info] 	at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
[info] 	at akka.cluster.JoinSeedNodeProcess$$anonfun$receive$4.applyOrElse(ClusterDaemon.scala:1562)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[info] 	at akka.cluster.JoinSeedNodeProcess.aroundReceive(ClusterDaemon.scala:1535)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[info] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] [INFO] [01/25/2019 22:53:44.525] [ClusterSystem-akka.actor.default-dispatcher-2] [akka.tcp://ClusterSystem@127.0.0.1:2551/] Message [akka.cluster.InternalClusterAction$InitJoin] from Actor[akka://ClusterSystem/system/cluster/core/daemon/joinSeedNodeProcess-1#1069204917] to Actor[akka.tcp://ClusterSystem@127.0.0.1:2551/] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka.tcp://ClusterSystem@127.0.0.1:2551/]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] [ERROR] [01/25/2019 22:53:44.525] [ClusterSystem-akka.actor.default-dispatcher-11] [akka.cluster.ClusterActorRefProvider] No root guardian at [akka.tcp://ClusterSystem@127.0.0.1:2552]
[info] java.lang.IllegalArgumentException: Wrong protocol of [akka.tcp://ClusterSystem@127.0.0.1:2552/], expected [akka]
[info] 	at akka.remote.RemoteActorRef.<init>(RemoteActorRefProvider.scala:533)
[info] 	at akka.remote.RemoteActorRefProvider.rootGuardianAt(RemoteActorRefProvider.scala:378)
[info] 	at akka.actor.ActorRefFactory.actorSelection(ActorRefProvider.scala:351)

```

**Comment by raboof** [comment]
Good catch, looks like we made a mistake in #96 . Could you try the `nettyForClusterScalaSample` branch?

**Comment by cosmir17** [comment]
Thanks, @raboof . It now runs properly.
```
[info] [INFO] [01/25/2019 23:51:18.069] [ClusterSystem-akka.actor.default-dispatcher-29] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:49929] - Welcome from [akka.tcp://ClusterSystem@127.0.0.1:2551]
[info] [INFO] [01/25/2019 23:51:18.071] [ClusterSystem-akka.actor.default-dispatcher-29] [akka.tcp://ClusterSystem@127.0.0.1:49929/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:2551
[info] [INFO] [01/25/2019 23:51:18.077] [ClusterSystem-akka.actor.default-dispatcher-14] [akka.tcp://ClusterSystem@127.0.0.1:2552/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:2551
[info] [INFO] [01/25/2019 23:51:18.643] [ClusterSystem-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is moving node [akka.tcp://ClusterSystem@127.0.0.1:2552] to [Up]
[info] [INFO] [01/25/2019 23:51:18.643] [ClusterSystem-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is moving node [akka.tcp://ClusterSystem@127.0.0.1:49929] to [Up]
[info] [INFO] [01/25/2019 23:51:18.644] [ClusterSystem-akka.actor.default-dispatcher-24] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:2552
[info] [INFO] [01/25/2019 23:51:18.644] [ClusterSystem-akka.actor.default-dispatcher-24] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:49929
[info] [INFO] [01/25/2019 23:51:18.662] [ClusterSystem-akka.actor.default-dispatcher-23] [akka.tcp://ClusterSystem@127.0.0.1:49929/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:2552
[info] [INFO] [01/25/2019 23:51:18.662] [ClusterSystem-akka.actor.default-dispatcher-23] [akka.tcp://ClusterSystem@127.0.0.1:49929/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:49929
[info] [INFO] [01/25/2019 23:51:18.864] [ClusterSystem-akka.actor.default-dispatcher-2] [akka.tcp://ClusterSystem@127.0.0.1:2552/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:2552
[info] [INFO] [01/25/2019 23:51:18.864] [ClusterSystem-akka.actor.default-dispatcher-2] [akka.tcp://ClusterSystem@127.0.0.1:2552/user/clusterListener] Member is Up: akka.tcp://ClusterSystem@127.0.0.1:49929

```

Alas, there is one error that doesn't impact the execution of the sample app. I only saw it when I first ran the application. It doesn't show up afterwards. It appears only if the application folder gets deleted and pulled it again from the repository.
```
[error] no libsigar-universal64-macosx.dylib in java.library.path
[error] org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path
[error]         at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:174)
[error]         at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:102)
[error]         at akka.cluster.metrics.SigarProvider.verifiedSigarInstance(Provision.scala:47)
```

**Comment by pysaumont** [comment]
It works with Netty, but this error also occurs with Artery. Is there anything to do to make it work ?

**Comment by pysaumont** [comment]
Forget about the question above. My mistake!
